task-2:solution
BorisYermolenko/JavaPractice pull request #2
Opened 2024-11-19 11:57 UTC by BorisYermolenko

2024-11-20 13:07 UTC, MiraGlaceon requested changes

2024-11-20 13:07 UTC, MiraGlaceon commented on src/com/javapractice/task2/Main.java
> +/*
У тебя нет нужных импортов (например, на класс Scanner). Попробуй самостоятельно разобраться что это такое и добавь их в задачу. 
Сейчас тебе в Идее класс Scanner подчеркнут красным, попробуй нажать Alt+Enter и выбрать нужный импорт. Напиши вкратце, для чего нужны импорты

2024-11-21 11:06 UTC, BorisYermolenko commented on src/com/javapractice/task2/Main.java
> +/*
импорты используются для подключения пакетов, классов из других файлов и библиотек

2024-11-22 11:13 UTC, MiraGlaceon approved these changes

2024-11-22 11:33 UTC, merged